### ISSUE TITLE
mute插件报错

### ISSUE THREAD

**Issue by ATTomatoo** [zhenxun-org/zhenxun_bot_plugins#18]
系统版本：Ubuntu 20.04
真寻版本：dev-v0.2.2
只要超级管理员用户一发消息，后台就这样报错，其他人就正常的
![H7UC}Q1HBATF2`L MQHMLQJ](https://github.com/user-attachments/assets/c78e98ef-88cd-4a4c-bef6-c074048fd9f1)

**Comment by HibiKier** [comment]
把ban_console里的重复数据删掉，一般是程序卡主后突然通了后导致多条数据同时加入数据库

**Comment by ATTomatoo** [comment]
删除重复数据后好了
