### ISSUE TITLE
b站订阅插件问题

### ISSUE THREAD

**Issue by am-q** [zhenxun-org/zhenxun_bot_plugins#2]
![1](https://github.com/user-attachments/assets/c56864fd-2a4d-4676-813a-37c9a94629a5)
b站订阅这个插件，监控没问题，发送的时候就会这样

**Comment by xuanerwa** [comment]
已更新

**Comment by am-q** [comment]
![image](https://github.com/user-attachments/assets/49bffde4-de1e-46ca-bd94-e5e0e3bbe635)
更新后提示这个,完整截图
