### ISSUE TITLE
真寻日报返回图片问题

### ISSUE THREAD

**Issue by ATTomatoo** [zhenxun-org/zhenxun_bot_plugins#31]
这是报错日志日志
[2024-10-14.log](https://github.com/user-attachments/files/17356319/2024-10-14.log)
[error_2024-10-14.log](https://github.com/user-attachments/files/17356320/error_2024-10-14.log)
这是开了代理之后正常返回日志
[2024-10-14-1.log](https://github.com/user-attachments/files/17356336/2024-10-14-1.log)
所有api都可以在无代理情况下正常访问，这里就放了ping的截图
![J)D}OAN0L%((A0CW6%)A3H4](https://github.com/user-attachments/assets/fefaf2dd-4e41-46b9-9c0c-af36e799d01c)

**Comment by ATTomatoo** [comment]
多试几次可以返回了，但是失败次数大于成功次数

**Comment by ATTomatoo** [comment]
https://github.com/vikiboss/60s/issues/13 
60秒域名污染导致的

**Comment by ATTomatoo** [comment]
60秒域名污染导致的

**Comment by HibiKier** [comment]
刚刚试了下可以访问

**Comment by ATTomatoo** [comment]
部分地区无法直接访问https://github.com/vikiboss/60s/issues/13，
为其添加alapi#34
