### ISSUE TITLE
微博热搜功能无法查看具体热搜页面

### ISSUE THREAD

**Issue by webjoin111** [zhenxun-org/zhenxun_bot_plugins#38]
能够显示热搜, 但是"微博热搜 [ID]"查看具体条目时会报错.
![image](https://github.com/user-attachments/assets/4132bf22-d452-4edf-b795-92372bf6c49a)

**Comment by HibiKier** [comment]
ab5e4edacd1e6b4a17e970d6cfc2c713e0fc472e
