### ISSUE TITLE
blackword未正确触发相应等级

### ISSUE THREAD

**Issue by ATTomatoo** [zhenxun-org/zhenxun_bot_plugins#42]
用的默认配置，就只是在原有词库里添加了一些词汇，但是在群里，触发会显示触发  负2 级 ，且只有提示，没有任何处罚

![1](https://github.com/user-attachments/assets/311f8d0a-7488-413b-b095-1327c099be62)

`11-30 23:16:30 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1011009339 from 2071459599@[群:933264645] '[at:qq=1633813628] 大傻逼'
11-30 23:16:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:30 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1146602371 from 2920101679@[群:677717015] '[image:summary=[动画表情],file=000001464e61704361744f6e65426f747c4d736746696c657c327c3637373731373...,sub_type=1,file_id=000001464e61704361744f6e65426f747c4d736746696c657c327c3637373731373...,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRLHCMz...,file_size=207066,file_unique=55a52ae5b9ae5ba39fc5339c37f4efbe]'
11-30 23:16:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:16:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-30 23:16:31 [INFO] zhenxun | 群聊[933264645] 用户[2071459599] CMD[敏感词警察] 添加至黑名单词汇记录 Black_word：shabi Plant_text：大傻逼
11-30 23:16:31 [INFO] zhenxun | BlackWord USER 2071459599 触发 -2 级惩罚...
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:16:31 [INFO] zhenxun | 下载 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRLHCMz-36alvD_pESOJRQ1ODnUYxja0Qwg_woo1b2h5qyEigMyBHByb2RQgL2jAVoQaxtpfCv5B0bhomZHVlP0KQ&rkey=CAQSKAB6JWENi5LMCt80rNNXP1AljmDadFf10_zio90hjhBWhk13JROha80 成功.. Path：/opt/zhenxun_bot-dev/resources/temp/compare_download__mute__img.jpg
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:16:31 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:16:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:16:32 [INFO] zhenxun | 下载 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRLHCMz-36alvD_pESOJRQ1ODnUYxja0Qwg_woo1b2h5qyEigMyBHByb2RQgL2jAVoQaxtpfCv5B0bhomZHVlP0KQ&rkey=CAQSKAB6JWENi5LMCt80rNNXP1AljmDadFf10_zio90hjhBWhk13JROha80 成功.. Path：/opt/zhenxun_bot-dev/resources/temp/compare_download_677717015_img.jpg
11-30 23:16:32 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:16:34 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 235092550 from 2071459599@[群:933264645] '[at:qq=1633813628] 大傻逼'
11-30 23:16:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:34 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:34 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:16:34 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:35 [INFO] zhenxun | 群聊[933264645] 用户[2071459599] CMD[敏感词警察] 添加至黑名单词汇记录 Black_word：shabi Plant_text：大傻逼
11-30 23:16:35 [INFO] zhenxun | BlackWord USER 2071459599 触发 -2 级惩罚...
11-30 23:16:35 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:16:36 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 982609671 from 3055326061@[群:933264645] '哈哈哈'
11-30 23:16:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:36 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running is cancelled
11-30 23:16:36 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:36 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running is cancelled
11-30 23:16:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:16:36 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running is cancelled
11-30 23:16:38 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 174882127 from 2071459599@[群:933264645] '[at:qq=1633813628] 大傻逼'
11-30 23:16:38 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:38 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:38 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:38 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:16:38 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:38 [INFO] zhenxun | 群聊[933264645] 用户[2071459599] CMD[敏感词警察] 添加至黑名单词汇记录 Black_word：shabi Plant_text：大傻逼
11-30 23:16:38 [INFO] zhenxun | BlackWord USER 2071459599 触发 -2 级惩罚...
11-30 23:16:38 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:16:42 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1866633736 from 3055326061@[群:933264645] '@Mahiro 大傻逼'
11-30 23:16:42 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:42 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:42 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running is cancelled
11-30 23:16:42 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:42 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:43 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running is cancelled
11-30 23:16:43 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:16:43 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running is cancelled
11-30 23:16:46 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 350911599 from 2920101679@[群:677717015] '怎么说，璃桑'
11-30 23:16:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:46 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:46 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:16:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-30 23:16:46 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-30 23:16:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:46 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:16:47 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:16:47 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:16:49 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 84738038 from 2071459599@[群:933264645] '[at:qq=1633813628] 大傻逼'
11-30 23:16:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:49 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:49 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:16:49 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:49 [INFO] zhenxun | 群聊[933264645] 用户[2071459599] CMD[敏感词警察] 添加至黑名单词汇记录 Black_word：shabi Plant_text：大傻逼
11-30 23:16:49 [INFO] zhenxun | BlackWord USER 2071459599 触发 -2 级惩罚...
11-30 23:16:49 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:16:52 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 780640440 from 3055326061@[群:933264645] '忘了我被拉进小黑屋了'
11-30 23:16:52 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:16:52 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:16:52 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running is cancelled
11-30 23:16:52 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:16:52 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:16:53 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running is cancelled
11-30 23:16:53 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:16:53 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running is cancelled
11-30 23:17:00 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 240062194 from 2071459599@[群:933264645] '笑死'
11-30 23:17:00 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:00 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:00 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:00 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:00 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:00 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:00 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:00 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:05 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 114548660 from 2379026862@[群:933264645] '这位更是重量级'
11-30 23:17:05 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:05 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:05 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:05 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:05 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:06 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:06 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:06 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:09 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1895311267 from 3255835276@[群:602632179] '[image:summary=,file=000001464e61704361744f6e65426f747c4d736746696c657c327c3630323633323...,sub_type=0,file_id=000001464e61704361744f6e65426f747c4d736746696c657c327c3630323633323...,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRaHbyg...,file_size=297051,file_unique=d0a036225f72d6d974be67e2d5140562]'
11-30 23:17:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:09 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-30 23:17:09 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-30 23:17:09 [INFO] zhenxun | 下载 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRaHbygEQ2gFMCSLo0yuMz66OLSWRjbkBIg_woo4cmK-KyEigMyBHByb2RQgL2jAVoQua-atOkmiqcdqSEW53q3hQ&rkey=CAQSKAB6JWENi5LMCt80rNNXP1AljmDadFf10_zio90hjhBWhk13JROha80 成功.. Path：/opt/zhenxun_bot-dev/resources/temp/compare_download__mute__img.jpg
11-30 23:17:09 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:09 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:10 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:10 [INFO] zhenxun | 下载 https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=EhRaHbygEQ2gFMCSLo0yuMz66OLSWRjbkBIg_woo4cmK-KyEigMyBHByb2RQgL2jAVoQua-atOkmiqcdqSEW53q3hQ&rkey=CAQSKAB6JWENi5LMCt80rNNXP1AljmDadFf10_zio90hjhBWhk13JROha80 成功.. Path：/opt/zhenxun_bot-dev/resources/temp/compare_download_602632179_img.jpg
11-30 23:17:10 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:12 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 346553793 from 3255835276@[群:602632179] '画完了画完了'
11-30 23:17:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:12 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:12 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-30 23:17:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-30 23:17:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:13 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:13 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:16 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1479487113 from 2071459599@[群:933264645] '笑喷'
11-30 23:17:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:16 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:16 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:16 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:16 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:16 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:29 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 301071972 from 2071459599@[群:933264645] '[at:qq=3055326061] 怎么做到的'
11-30 23:17:29 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:29 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:29 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:29 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:29 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:29 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:29 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:29 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:30 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 884701641 from 2558567903@[群:602632179] '[image:summary=,file=000000a64e61704361744f6e65426f747c4d736746696c657c327c3630323633323...,sub_type=0,file_id=000000a64e61704361744f6e65426f747c4d736746696c657c327c3630323633323...,url=https://gchat.qpic.cn/gchatpic_new/0/0-0-D8625EFFFC20C7272780A33856...,file_size=23908,file_unique=d8625efffc20c7272780a33856c53171]'
11-30 23:17:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:30 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-30 23:17:30 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-30 23:17:30 [INFO] zhenxun | 下载 https://gchat.qpic.cn/gchatpic_new/0/0-0-D8625EFFFC20C7272780A33856C53171/0 成功.. Path：/opt/zhenxun_bot-dev/resources/temp/compare_download__mute__img.jpg
11-30 23:17:30 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:30 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:30 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:31 [INFO] zhenxun | 下载 https://gchat.qpic.cn/gchatpic_new/0/0-0-D8625EFFFC20C7272780A33856C53171/0 成功.. Path：/opt/zhenxun_bot-dev/resources/temp/compare_download_602632179_img.jpg
11-30 23:17:31 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:32 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1245996781 from 2558567903@[群:602632179] '神秘代码'
11-30 23:17:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:32 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:32 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
11-30 23:17:32 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
11-30 23:17:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:32 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
11-30 23:17:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
11-30 23:17:32 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
11-30 23:17:33 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1014719608 from 2071459599@[群:933264645] '[at:qq=1633813628] 大傻逼'
11-30 23:17:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
11-30 23:17:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
11-30 23:17:33 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
11-30 23:17:33 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
11-30 23:17:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
11-30 23:17:33 [INFO] zhenxun | 群聊[933264645] 用户[2071459599] CMD[敏感词警察] 添加至黑名单词汇记录 Black_word：shabi Plant_text：大傻逼
11-30 23:17:33 [INFO] zhenxun | BlackWord USER 2071459599 触发 -2 级惩罚...`

**Comment by HibiKier** [comment]
https://github.com/zhenxun-org/zhenxun_bot_plugins/pull/49 尝试更新

**Comment by ATTomatoo** [comment]
更新了，找到问题的关键了
`12-17 19:51:48 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 259421377 from 912230763@[群:602632179] '[at:qq=1633813628] 让我闻闻内裤'
12-17 19:51:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
12-17 19:51:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
12-17 19:51:48 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
12-17 19:51:48 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
12-17 19:51:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
12-17 19:51:48 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
12-17 19:51:48 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
12-17 19:51:48 [INFO] zhenxun | 群聊[602632179] 用户[912230763] CMD[敏感词警察] 添加至黑名单词汇记录 Black_word：内裤 Plant_text：让我闻闻内裤
12-17 19:51:48 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
12-17 19:51:56 [SUCCESS] nonebot | OneBot V11 1633813628 | [message.group.normal]: Message 1392436312 from 912230763@[群:602632179] '不行'
12-17 19:51:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32)
12-17 19:51:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39)
12-17 19:51:56 [INFO] nonebot | Matcher(type='message', module=zhenxun.builtin_plugins.chat_history.chat_message, lineno=39) running complete
12-17 19:51:56 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.mute.mute_message, lineno=32) running complete
12-17 19:51:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53)
12-17 19:51:56 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.parse_bilibili, lineno=53) running complete
12-17 19:51:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32)
12-17 19:51:56 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.black_word.black_watch, lineno=32) running complete
12-17 19:51:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96)
12-17 19:51:56 [INFO] nonebot | Matcher(type='message', module=zhenxun.plugins.fudu, lineno=96) running complete
`
![f8e1d94f-2f9d-41f9-85ed-c21aff041989](https://github.com/user-attachments/assets/221b4a79-6ed8-46b2-a136-5a57517f4290)
![_17344370299559](https://github.com/user-attachments/assets/27742834-c751-494c-a9e7-43036767c502)

这段回复为触发了关键词的部分，类似模糊词，上次触发显示为 负二级，这次为负一级，但是这次没有在群里有任何回应

**Comment by HibiKier** [comment]
试试把这表清空重新触发

**Comment by ATTomatoo** [comment]
清空了，正常了
