### ISSUE TITLE
send_setu插件帮助信息与指令匹配器不符

### ISSUE THREAD

**Issue by MWTJC** [zhenxun-org/zhenxun_bot_plugins#45]
如题，对于多张图片的发送指令，实际代码比帮助信息多出了前置动词，造成根据帮助信息编写指令无法发送多张图片：
[/plugins/send_setu_/send_setu
/__init__.py](https://github.com/zhenxun-org/zhenxun_bot_plugins/tree/main/plugins/send_setu_/send_setu/__init__.py#L163)

**Comment by HibiKier** [comment]
[feature/fix-setu-a](https://github.com/zhenxun-org/zhenxun_bot_plugins/pull/48) 已更新

**Comment by MWTJC** [comment]
感谢
